version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crime_management
    ports:
      - "5432:5432"
    volumes:
      # - pg-data:/var/lib/postgresql/data
      - ../internal/database/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: crime_management

      MINIO_ENDPOINT: minio
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

      APP_PORT: 8080
      JWT_SECRET: thisissosecretprobably

    ports:
      - "8080:8080"

volumes:
  # pg-data:
  minio-data:
